# Generated by Django 5.1.7 on 2025-03-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApoyoProfesoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion_doc', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identidad', models.BinaryField()),
                ('tarjeta_servicio_militar', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_estudio', models.CharField(max_length=50)),
                ('graduado', models.BooleanField()),
                ('fecha_de_graduacion', models.DateField()),
                ('institucion_estudio', models.CharField(max_length=50)),
                ('titulo_obtenido', models.CharField(max_length=50)),
                ('titulo_convalidado', models.CharField(max_length=50)),
                ('fecha_de_convalidacion', models.DateField(blank=True, null=True)),
                ('resolucion_de_convalidacion', models.CharField(blank=True, max_length=50, null=True)),
                ('pais_estudio', models.CharField(max_length=50)),
                ('departamento_estudio', models.CharField(max_length=50)),
                ('ciudad_estudio', models.CharField(max_length=50)),
                ('fecha_de_inicio_est', models.DateField()),
                ('fecha_de_finalizacion_est', models.DateField()),
                ('certificado_est', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_experiencia', models.CharField(max_length=50)),
                ('experiencia_ottenida', models.CharField(max_length=50)),
                ('institucion_exp', models.CharField(max_length=100)),
                ('trabajo_actual', models.BooleanField()),
                ('cargo', models.CharField(max_length=50)),
                ('intensidad', models.CharField(max_length=50)),
                ('fecha_de_inicio_exp', models.DateField()),
                ('fecha_de_finalizacion_exp', models.DateField()),
                ('certificado_exp', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='InformacionContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais_info', models.CharField(max_length=50)),
                ('departamento_info', models.CharField(max_length=50)),
                ('ciudad_info', models.CharField(max_length=50)),
                ('direccion_info', models.CharField(max_length=50)),
                ('barrio_info', models.CharField(max_length=50)),
                ('telefono_fijo', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_celular', models.CharField(max_length=50)),
                ('correo_electronico', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProduccionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_produccion', models.CharField(max_length=50)),
                ('titulo_de_produccion', models.CharField(max_length=50)),
                ('autores', models.CharField(max_length=50)),
                ('fecha_de_publicacion', models.DateField()),
                ('indexada_de', models.CharField(max_length=50)),
                ('base_de_datos', models.CharField(max_length=50)),
                ('institucion_pit', models.CharField(max_length=50)),
                ('pais_pit', models.CharField(max_length=50)),
                ('departamento_pit', models.CharField(max_length=50)),
                ('ciudad_pit', models.CharField(max_length=50)),
                ('tipo_de_participacion', models.CharField(max_length=50)),
                ('archivo_de_produccion', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
